services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: event-app
    container_name: event-app
    restart: unless-stopped
    working_dir: /var/www
    ports:
      - "5173:5173"
    volumes:
      - ./:/var/www
    networks:
      - event-app-network

  nginx:
    image: nginx:alpine
    container_name: event-app-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - event-app-network

  db:
    image: mysql:8.0
    container_name: event-app-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: event_user
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - event-app-network

networks:
  event-app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
